// <auto-generated />
using System;
using Maway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maway.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200516194601_initial3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maway.Data.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Maway.Data.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyRegistryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyRegistryId")
                        .IsUnique()
                        .HasName("Item_Registry_Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyRegistryId = "KR123",
                            ItemTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyRegistryId = "KR124",
                            ItemTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CompanyRegistryId = "KR125",
                            ItemTypeId = 3
                        });
                });

            modelBuilder.Entity("Maway.Data.Model.ItemAttribute", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ItemAttribute","attributes");

                    b.HasData(
                        new
                        {
                            Key = "Gearbox",
                            Icon = "cog"
                        },
                        new
                        {
                            Key = "AirCondition",
                            Icon = "snowflage"
                        },
                        new
                        {
                            Key = "FuelType",
                            Icon = "gaspump"
                        },
                        new
                        {
                            Key = "Doors",
                            Icon = "dooropen"
                        });
                });

            modelBuilder.Entity("Maway.Data.Model.ItemAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttributeKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeKey");

                    b.HasIndex("ItemTypeId", "AttributeKey")
                        .IsUnique()
                        .HasName("Item_Attribute")
                        .HasFilter("[AttributeKey] IS NOT NULL");

                    b.ToTable("ItemAttributes","attributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeKey = "Gearbox",
                            ItemTypeId = 1,
                            Value = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            AttributeKey = "AirCondition",
                            ItemTypeId = 1,
                            Value = "Air condition"
                        });
                });

            modelBuilder.Entity("Maway.Data.Model.ItemPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("ItemTypePrices");
                });

            modelBuilder.Entity("Maway.Data.Model.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "someimage.png",
                            Title = "fiat 500"
                        },
                        new
                        {
                            Id = 2,
                            Image = "someimage.png",
                            Title = "fiat tipo"
                        },
                        new
                        {
                            Id = 3,
                            Image = "someimage.png",
                            Title = "leon"
                        },
                        new
                        {
                            Id = 4,
                            Image = "someimage.png",
                            Title = "vespa"
                        });
                });

            modelBuilder.Entity("Maway.Data.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Maway.Data.Model.OrderSupplements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplementsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SupplementsId");

                    b.ToTable("OrderSupplements");
                });

            modelBuilder.Entity("Maway.Data.Model.Supplements.Extras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Maway.Data.Model.Supplements.ItemExtras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtrasId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("ItemExtras");
                });

            modelBuilder.Entity("Maway.Data.Model.Item", b =>
                {
                    b.HasOne("Maway.Data.Model.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maway.Data.Model.ItemAttributes", b =>
                {
                    b.HasOne("Maway.Data.Model.ItemAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeKey");

                    b.HasOne("Maway.Data.Model.ItemType", "ItemType")
                        .WithMany("ItemAttributes")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maway.Data.Model.ItemPrice", b =>
                {
                    b.HasOne("Maway.Data.Model.ItemType", null)
                        .WithMany("ItemPrices")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maway.Data.Model.Order", b =>
                {
                    b.HasOne("Maway.Data.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Maway.Data.Model.Item", "Item")
                        .WithMany("ItemOrders")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("Maway.Data.Model.OrderSupplements", b =>
                {
                    b.HasOne("Maway.Data.Model.Order", "Order")
                        .WithMany("OrderExtras")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maway.Data.Model.Supplements.ItemExtras", "Supplements")
                        .WithMany()
                        .HasForeignKey("SupplementsId");
                });

            modelBuilder.Entity("Maway.Data.Model.Supplements.ItemExtras", b =>
                {
                    b.HasOne("Maway.Data.Model.Supplements.Extras", "Extras")
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maway.Data.Model.ItemType", "ItemType")
                        .WithMany("ItemExtras")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
